/**
 * Sprite manifest format.
 *
 * This is the contract between the offline packer (tools/pack-sprites.mjs) and
 * the runtime renderer. It is designed against the shape the AoE2 DE scrape
 * already produces, described in age-of-kings-qatar's assets/raw/SCRAPE_INDEX.md:
 *
 *     gfx/graphics/<sprite>/
 *       meta.json     frames[]: { canvas w/h, hotspot, layers{...}.bbox }
 *       fNNN.png      main RGBA
 *       fNNN_s.png    shadow alpha
 *       fNNN_p.png    player-colour mask
 *       fNNN_d.png    damage overlay
 *
 * Those four layers are the whole reason a faithful AoE2 look is achievable at
 * all. Separating the player-colour mask from the base sprite is the hard part
 * of the original SLP/SLD format, and the scrape has already done it.
 *
 * ── Why not a plain PixiJS spritesheet ───────────────────────────────────────
 *
 * A standard spritesheet has no concept of a facing angle, and an isometric RTS
 * needs one: a knight has (typically) 5 stored angles mirrored to 8, per
 * animation, per frame. That third dimension is what this format adds — plus
 * per-frame hotspots, which decide where a sprite's feet sit on the tile.
 * Get hotspots wrong and every unit floats or sinks.
 */

/** One animation of one unit/building, e.g. "attackA" or "walk". */
export interface AnimationManifest {
  /** Animation name as it appears in the source sprite id, e.g. "attackA". */
  name: string
  /** Number of distinct facing directions stored (before mirroring). */
  storedAngles: number
  /**
   * Total facing directions presented to the game. When this exceeds
   * storedAngles the extra ones are horizontal mirrors — the same trick AoE2
   * itself uses to halve sprite storage.
   */
  angles: number
  /** Frames per angle. */
  frameCount: number
  /** Seconds for one complete cycle. */
  duration: number
  /** Whether playback repeats (walk) or holds on the last frame (die). */
  loop: boolean
  /**
   * Frame lookup table, indexed [angle][frame] -> index into `frames`.
   * A negative value means "use `-(v+1)` mirrored horizontally".
   */
  lookup: number[][]
}

/** One packed frame's placement within an atlas page. */
export interface FrameManifest {
  /** Atlas page index. */
  page: number
  /** Rect within the page, in pixels. */
  x: number
  y: number
  w: number
  h: number
  /**
   * Anchor point in pixels, relative to the frame's top-left.
   *
   * This is the sprite's hotspot: the point that sits exactly on the unit's
   * world position. AoE2 puts it at the character's feet, which is what makes
   * depth sorting and tile occupancy line up.
   */
  anchorX: number
  anchorY: number
}

/** Layers a sprite may carry. `main` is mandatory; the rest are optional. */
export interface LayerPages {
  main: string[]
  /** Soft shadow, drawn beneath everything in a separate pass. */
  shadow?: string[]
  /** Greyscale mask; non-zero pixels are tinted with the owner's colour. */
  player?: string[]
  /** Damage overlay for buildings, cross-faded by remaining HP. */
  damage?: string[]
}

export interface SpriteManifest {
  /** Sprite id, e.g. "u_cav_knight". */
  id: string
  /** Atlas page filenames per layer, relative to the manifest. */
  pages: LayerPages
  /** Page dimensions, shared by every layer. */
  pageWidth: number
  pageHeight: number
  /** Flat frame table; animations index into this. */
  frames: FrameManifest[]
  /** Animations by name. */
  animations: Record<string, AnimationManifest>
}

export interface SpriteLibraryManifest {
  version: 1
  /** Generated by tools/pack-sprites.mjs; recorded for provenance. */
  generator: string
  sprites: Record<string, SpriteManifest>
}

/**
 * Map a world-space facing angle onto a sprite angle bucket.
 *
 * Returns the frame-table index plus whether it must be drawn mirrored.
 * Kept here rather than in the renderer so the packer and the runtime cannot
 * disagree about the convention — the single most common source of
 * "all my units face the wrong way" bugs.
 */
export function resolveFrame(
  anim: AnimationManifest,
  angleIndex: number,
  frameIndex: number,
): { frame: number; mirrored: boolean } {
  const row = anim.lookup[angleIndex % anim.angles]
  if (!row) return { frame: 0, mirrored: false }
  const v = row[frameIndex % anim.frameCount] ?? 0
  return v < 0 ? { frame: -(v + 1), mirrored: true } : { frame: v, mirrored: false }
}

/** Which frame of an animation is showing at time `t` seconds. */
export function frameAt(anim: AnimationManifest, t: number): number {
  if (anim.frameCount <= 1) return 0
  const per = anim.duration / anim.frameCount
  const raw = Math.floor(t / per)
  return anim.loop ? raw % anim.frameCount : Math.min(raw, anim.frameCount - 1)
}
